import data:
```{r}
library(stars)
load("sampling.rda")
r = read_stars(c("NDVI2019_ClassificationImg_10m.tif",
  "NDVI2020_ClassificationImg_10m.tif",
  "NDVI2021_ClassificationImg_10m.tif",
  "NDVI2022_ClassificationImg_10m.tif")) |> merge() |> setNames("NDVI")
r
p = st_read("PixelCoordinates_Polygon.geojson")
```

```{r}
library(dplyr)
st_downsample(r, c(1,1,0)) |> st_apply(3, mean) |> pull(1)
st_downsample(r, c(4,4,0)) |> st_apply(3, mean) |> pull(1)
st_downsample(r, c(9,9,0)) |> st_apply(3, mean) |> pull(1)
st_downsample(r, c(19,19,0)) |> st_apply(3, mean) |> pull(1)
st_downsample(r, c(49,49,0)) |> st_apply(3, mean) |> pull(1)
st_downsample(r, c(99,99,0)) |> st_apply(3, mean) |> pull(1)
st_downsample(r, c(199,199,0)) |> st_apply(3, mean) |> pull(1)
```

```{r}
year = 2019:2022
r |> st_apply(3, mean) |> pull(1) -> x
calc_f = function(ds, cellsize) {
  st_downsample(r, c(ds,ds,0)) |> st_apply(3, mean) |> pull(1) -> y
  e = se[[cellsize]]
  ylim = c(min(1.15, min(y) - 2 * e), max(1.28, max(y) + 2 * e))
  data.frame(year = year, ref = x-1, 
	cellsize = as.numeric(cellsize), fraction = y-1, err = e,
  	emin = pmax(0, y-1-2*e), emax = pmin(.3, y-1+2*e))
}

ds = c(1, 4, 9, 19, 49, 99, 199, 499, 999)
cs = c( "20", "50", "100", "200", "500", "1000", "2000", "5000", "10000")
all = do.call(rbind, mapply(calc_f, ds, cs, SIMPLIFY = FALSE))
```

```{r}
#tiff("/tmp/res.tif", 15, 10, units = "in", res = 300)
library(ggplot2)
f = function(x) data.frame(cellsize = paste(x$cellsize, "m"))
ggplot(all, aes(x = year, group = cellsize)) +
  geom_line(aes(y = ref), lwd = 3, col = 'grey') +
  geom_point(aes(y = fraction)) +
  geom_line(aes(y = fraction), lty = 2) +
  facet_wrap(cellsize ~., ncol = 3, labeller = f) + 
  labs(x = "Year", y = "Forest Cover (fraction)",
       title = "") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold")) + 
  geom_errorbar(aes(ymin=fraction-2*err, ymax=fraction+2*err),width=0.2) +
  geom_errorbar(aes(ymin=emin, ymax=emax), width=0.2) +
  ylim(0, .3)
#dev.off()
```
